### ISSUE TITLE
trying to get the docker-compose that is in /examples folder to work

### ISSUE THREAD

**Issue by petersmiddy** [claroty/jwthenticator#26]
Hello, the postgres container is starting properly, creating the 'jwthenticator' database, and listening on port 5432.  However, the jwthenticator is not able to connect to it.  It keeps failing with this error:

$ docker compose up
[+] Running 3/2
 ⠿ Network examples_default            Created                                                                                                                                                                                      0.0s
 ⠿ Container examples-postgres-1       Created                                                                                                                                                                                      0.1s
 ⠿ Container examples-jwthenticator-1  Created                                                                                                                                                                                      0.1s
Attaching to examples-jwthenticator-1, examples-postgres-1
examples-postgres-1       | The files belonging to this database system will be owned by user "postgres".
examples-postgres-1       | This user must also own the server process.
examples-postgres-1       | 
examples-postgres-1       | The database cluster will be initialized with locale "en_US.utf8".
examples-postgres-1       | The default database encoding has accordingly been set to "UTF8".
examples-postgres-1       | The default text search configuration will be set to "english".
examples-postgres-1       | 
examples-postgres-1       | Data page checksums are disabled.
examples-postgres-1       | 
examples-postgres-1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
examples-postgres-1       | creating subdirectories ... ok
examples-postgres-1       | selecting dynamic shared memory implementation ... posix
examples-postgres-1       | selecting default max_connections ... 100
examples-postgres-1       | selecting default shared_buffers ... 128MB
examples-postgres-1       | selecting default time zone ... Etc/UTC
examples-postgres-1       | creating configuration files ... ok
examples-postgres-1       | running bootstrap script ... ok
examples-postgres-1       | performing post-bootstrap initialization ... ok
examples-postgres-1       | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
examples-postgres-1       | You can change this by editing pg_hba.conf or using the option -A, or
examples-postgres-1       | --auth-local and --auth-host, the next time you run initdb.
examples-postgres-1       | ok
examples-postgres-1       | 
examples-postgres-1       | 
examples-postgres-1       | Success. You can now start the database server using:
examples-postgres-1       | 
examples-postgres-1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
examples-postgres-1       | 
examples-postgres-1       | waiting for server to start....2022-02-09 14:00:07.495 UTC [49] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
examples-postgres-1       | 2022-02-09 14:00:07.497 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
examples-postgres-1       | 2022-02-09 14:00:07.504 UTC [50] LOG:  database system was shut down at 2022-02-09 14:00:07 UTC
examples-postgres-1       | 2022-02-09 14:00:07.508 UTC [49] LOG:  database system is ready to accept connections
examples-postgres-1       |  done
examples-postgres-1       | server started
examples-postgres-1       | CREATE DATABASE
examples-postgres-1       | 
examples-postgres-1       | 
examples-postgres-1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
examples-postgres-1       | 
examples-postgres-1       | 2022-02-09 14:00:07.779 UTC [49] LOG:  received fast shutdown request
examples-postgres-1       | waiting for server to shut down....2022-02-09 14:00:07.780 UTC [49] LOG:  aborting any active transactions
examples-postgres-1       | 2022-02-09 14:00:07.782 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
examples-postgres-1       | 2022-02-09 14:00:07.783 UTC [51] LOG:  shutting down
examples-postgres-1       | 2022-02-09 14:00:07.793 UTC [49] LOG:  database system is shut down
examples-postgres-1       |  done
examples-postgres-1       | server stopped
examples-postgres-1       | 
examples-postgres-1       | PostgreSQL init process complete; ready for start up.
examples-postgres-1       | 
examples-postgres-1       | 2022-02-09 14:00:07.898 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
examples-postgres-1       | 2022-02-09 14:00:07.898 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
examples-postgres-1       | 2022-02-09 14:00:07.898 UTC [1] LOG:  listening on IPv6 address "::", port 5432
examples-postgres-1       | 2022-02-09 14:00:07.900 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
examples-postgres-1       | 2022-02-09 14:00:07.904 UTC [63] LOG:  database system was shut down at 2022-02-09 14:00:07 UTC
examples-postgres-1       | 2022-02-09 14:00:07.908 UTC [1] LOG:  database system is ready to accept connections
examples-jwthenticator-1  | Traceback (most recent call last):
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
examples-jwthenticator-1  |     return _run_code(code, main_globals, None,
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
examples-jwthenticator-1  |     exec(code, run_globals)
examples-jwthenticator-1  |   File "/opt/jwthenticator/server.py", line 15, in <module>
examples-jwthenticator-1  |     from jwthenticator.api import JWThenticatorAPI
examples-jwthenticator-1  |   File "/opt/jwthenticator/api.py", line 11, in <module>
examples-jwthenticator-1  |     from jwthenticator.tokens import TokenManager
examples-jwthenticator-1  |   File "/opt/jwthenticator/tokens.py", line 11, in <module>
examples-jwthenticator-1  |     from jwthenticator.models import Base, RefreshTokenInfo
examples-jwthenticator-1  |   File "/opt/jwthenticator/models.py", line 40, in <module>
examples-jwthenticator-1  |     if not database_exists(DB_URI):
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 494, in database_exists
examples-jwthenticator-1  |     return bool(_get_scalar_result(engine, text))
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 448, in _get_scalar_result
examples-jwthenticator-1  |     with engine.connect() as conn:
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
examples-jwthenticator-1  |     return self._connection_cls(self, **kwargs)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
examples-jwthenticator-1  |     else engine.raw_connection()
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
examples-jwthenticator-1  |     return self._wrap_pool_connect(
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
examples-jwthenticator-1  |     return fn()
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
examples-jwthenticator-1  |     return _ConnectionFairy._checkout(self)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
examples-jwthenticator-1  |     fairy = _ConnectionRecord.checkout(pool)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
examples-jwthenticator-1  |     rec = pool._do_get()
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
examples-jwthenticator-1  |     self._dec_overflow()
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
examples-jwthenticator-1  |     compat.raise_(
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
examples-jwthenticator-1  |     raise exception
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
examples-jwthenticator-1  |     return self._create_connection()
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
examples-jwthenticator-1  |     return _ConnectionRecord(self)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
examples-jwthenticator-1  |     self.__connect(first_connect_check=True)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
examples-jwthenticator-1  |     pool.logger.debug("Error on connect(): %s", e)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
examples-jwthenticator-1  |     compat.raise_(
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
examples-jwthenticator-1  |     raise exception
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
examples-jwthenticator-1  |     connection = pool._invoke_creator(self)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
examples-jwthenticator-1  |     return dialect.connect(*cargs, **cparams)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
examples-jwthenticator-1  |     return self.dbapi.connect(*cargs, **cparams)
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/pg8000/__init__.py", line 56, in connect
examples-jwthenticator-1  |     return Connection(
examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/pg8000/core.py", line 741, in __init__
examples-jwthenticator-1  |     self.message_types[code](self._read(data_len - 4), None)
**examples-jwthenticator-1  |   File "/usr/local/lib/python3.8/site-packages/pg8000/core.py", line 980, in handle_AUTHENTICATION_REQUEST
examples-jwthenticator-1  |     self.password.decode('utf8'))
examples-jwthenticator-1  | AttributeError: 'NoneType' object has no attribute 'decode'
examples-jwthenticator-1 exited with code 1`**

-------------------------------------
Here are the docker-compose.yml, and consts.py files I'm using.  Thank you so much in advance if you can assist.  

**docker-compose.yml**

`version: "3"

services:

      
    postgres:
        image: postgres
        ports:
            - 5432:5432
        # network_mode: host
        environment:
            - POSTGRES_NAME=jwthenticator
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD="password"
            - POSTGRES_DB=jwthenticator

    jwthenticator:
        image: clarotyltd/jwthenticator
        ports:
            - 8080:8080
        # network_mode: host
        environment:
            - DB_NAME=jwthenticator
            - DB_USER=postgres
            - DB_PASSWORD="password"
            - DB_HOST=postgres
        depends_on:
            - postgres`

**consts.py**

`from __future__ import absolute_import
from environs import Env
from sqlalchemy import create_engine

DAYS_TO_SECONDS = lambda x: x * 60 * 24

env = Env()

\# Server consts
PORT = env.int("PORT", 8080)
URL_PREFIX = URL_PREFIX = env.str("URL_PREFIX", "")
DISABLE_EXTERNAL_API = env.bool("DISABLE_EXTERNAL_API", False)
DISABLE_INTERNAL_API = env.bool("DISABLE_INTERNAL_API", False)

\# JWT consts
JWT_ALGORITHM = env.str("JWT_ALGORITHM", "RS256")
JWT_ALGORITHM_FAMILY = env.str("JWT_ALGORITHM_FAMILY", "RSA")
JWT_LEASE_TIME = env.int("JWT_LEASE_TIME", 30 * 60) # In seconds - 30 minutes
JWT_AUDIENCE = env.list("JWT_AUDIENCE", [])

\# Token consts
KEY_EXPIRY = env.int("KEY_EXPIRY", DAYS_TO_SECONDS(120))  # In seconds
REFRESH_TOKEN_EXPIRY = env.int("REFRESH_TOKEN_EXPIRY", DAYS_TO_SECONDS(60))   # In seconds

\# Keys from env
RSA_PUBLIC_KEY = env("RSA_PUBLIC_KEY", None)
RSA_PRIVATE_KEY = env("RSA_PRIVATE_KEY", None)
\# Keys from file
RSA_PUBLIC_KEY_PATH = env("RSA_PUBLIC_KEY_PATH", None)
RSA_PRIVATE_KEY_PATH = env("RSA_PRIVATE_KEY_PATH", None)
\# If no key is given, used for key generation
RSA_KEY_STRENGTH = env.int("RSA_KEY_SIZE", 2048)

\# DB consts
DB_CONNECTOR = env.str("DB_CONNECTOR", "postgresql+pg8000")
DB_USER = env.str("DB_USER", "postgres")
DB_PASS = env.str("DB_PASS", "password")
DB_HOST = env.str("DB_HOST", "postgres")
DB_NAME = env.str("DB_NAME", "jwthenticator")

DB_URI = env.str("DB_URI", f"{DB_CONNECTOR}://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}")
`

**Comment by guyzyl** [comment]
The problem is caused since you're setting the wrong password env var for the `jwthenticator` container.
It should be `DB_PASS`, not `DB_PASSWORD`.

**Comment by petersmiddy** [comment]
That was it!  Thank you so much.  Have a great day.
